repos:
- repo: https://github.com/lovesegfault/beautysh.git
  rev: v6.2.1
  hooks:
  - id: beautysh
- repo: https://github.com/Vimjas/vint.git
  rev: v0.4a4
  hooks:
  - id: vint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/executablebooks/mdformat.git
  rev: 0.7.14
  hooks:
  - id: mdformat
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=800]
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: fix-byte-order-marker
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
